---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "webscrapper"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webscrapper-scrapper"
  namespace: "webscrapper"
  labels:
    app: "webscrapper-scrapper"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "webscrapper-scrapper"
  template:
    metadata:
      labels:
        app: "webscrapper-scrapper"
    spec:
      containers:
      - name: "webscrapper-scrapper-sha256-1"
        image: "webscrapper-scrapper"
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: apiKey
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: appId
        - name: AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: authDomain
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: databaseURL
        - name: MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: messagingSenderId
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: projectId
        - name: STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: firebase-db
              key: storageBucket

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "webscrapper-scrapper-hpa-xa4q"
  namespace: "webscrapper"
  labels:
    app: "webscrapper-scrapper"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "webscrapper-scrapper"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
