---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "webscrapper"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webscrapper-scrapper"
  namespace: "webscrapper"
  labels:
    app: "webscrapper-scrapper"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "webscrapper-scrapper"
  template:
    metadata:
      labels:
        app: "webscrapper-scrapper"
    spec:
      serviceAccountName: pages-db-ksacc
      containers:
      - name: "webscrapper-scrapper-sha256-1"
        image: "webscrapper-scrapper"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-pages
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-pages
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-pages
              key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0 # make sure the use the latest version
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          - "-instances=pages-scrapper=tcp:5432"
        securityContext:
          runAsNonRoot: true

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "webscrapper-scrapper-hpa-xa4q"
  namespace: "webscrapper"
  labels:
    app: "webscrapper-scrapper"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "webscrapper-scrapper"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
