name: Deploy webscrapper to gke

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: webscrapper-71830
  GKE_CLUSTER: webscrapper-cluster
  GKE_ZONE: europe-central2
  DEPLOYMENT_NAME: webscrapper-deploy
  NEW_IMAGE: europe-central2-docker.pkg.dev/webscrapper-71830/webscrapper-repo/webscrapper-front:${{github.run_number}}
  SERVICE_NAME: webscrapper-front

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/886237649633/locations/global/workloadIdentityPools/webscrapper-github-pool/providers/webscrapper-github-provider'
        service_account: 'webscrapper-service@"$PROJECT_ID".iam.gserviceaccount.com'
    
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get gcloud credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$NEW_IMAGE" \
          ./webscrapper-front/

    - name: Giving access to zone
      run: |-
        gcloud auth configure-docker $GKE_ZONE-docker.pkg.dev

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$NEW_IMAGE"

    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        kustomize edit set image $SERVICE_NAME=$NEW_IMAGE
        kubectl apply -k .
        kubectl get services -o wide

